[program:napcarot-worker]
process_name=%(program_name)s_%(process_num)02d
directory=/var/www/napcarot.vn/laravel-app
command=/usr/bin/php artisan queue:work --queue=topup,mails,user-logs,default --sleep=3 --tries=3 --timeout=60 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/supervisor/napcarot-worker.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=10
stopwaitsecs=3600

[program:napcarot-scheduler]
process_name=%(program_name)s
directory=/var/www/napcarot.vn/laravel-app
command=/usr/bin/php artisan schedule:work
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/napcarot-scheduler.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=10
stopwaitsecs=60

[program:napcarot-reverb]
process_name=%(program_name)s
directory=/var/www/napcarot.vn/laravel-app
command=/usr/bin/php artisan reverb:start
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/napcarot-reverb.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=10
stopwaitsecs=60

[group:napcarot]
programs=napcarot-worker,napcarot-scheduler,napcarot-reverb
priority=999
