<?php

test('client mobile navigation uses an accessible off canvas drawer', function (): void {
    $projectRoot = dirname(__DIR__, 2);
    $layout = file_get_contents($projectRoot.'/resources/views/client/layouts/app.blade.php');
    $script = file_get_contents($projectRoot.'/resources/js/client.js');
    $styles = file_get_contents($projectRoot.'/resources/css/client.css');
    $boxicons = file_get_contents($projectRoot.'/public/assets/icon/boxicons/fonts/basic/boxicons.min.css');
    $accountOrders = file_get_contents($projectRoot.'/resources/views/client/account/orders/index.blade.php');
    $accountProfile = file_get_contents($projectRoot.'/resources/views/client/account/profile.blade.php');
    $wallet = file_get_contents($projectRoot.'/resources/views/client/account/wallet.blade.php');
    $topupGame = file_get_contents($projectRoot.'/resources/views/client/topup/game.blade.php');
    $payment = file_get_contents($projectRoot.'/resources/views/client/orders/payment.blade.php');
    $sharedPayment = file_get_contents($projectRoot.'/resources/views/components/client/bank-transfer-payment.blade.php');
    $contentPage = file_get_contents($projectRoot.'/resources/views/pages/content/show.blade.php');
    $seoIndex = file_get_contents($projectRoot.'/resources/views/pages/seo/index.blade.php');
    $floatingSupport = file_get_contents($projectRoot.'/resources/views/components/client/floating-support.blade.php');

    expect($layout)
        ->toContain('width=device-width, initial-scale=1, viewport-fit=cover')
        ->toContain('<x-boxicon />')
        ->toContain('bx bx-home-alt-2')
        ->toContain('bx bx-wallet-alt')
        ->toContain('bx bx-history')
        ->toContain('bx bx-news')
        ->toContain('id="main-content" class="min-w-0 focus:outline-none" tabindex="-1" data-page-enter')
        ->toContain('class="sticky top-0 z-50 border-b border-slate-200 bg-white/95 backdrop-blur lg:z-40"')
        ->toContain('class="fixed inset-0 z-[70] lg:hidden" data-mobile-menu aria-hidden="true" hidden')
        ->toContain('data-menu-backdrop')
        ->toContain('data-menu-panel')
        ->toContain('data-menu-item')
        ->toContain('data-menu-icon-open')
        ->toContain('data-menu-icon-close')
        ->toContain('data-mobile-sidebar-toggle')
        ->toContain('data-mobile-bottom-nav')
        ->toContain('data-mobile-nav-item="topup"')
        ->toContain('data-mobile-nav-item="wallet"')
        ->toContain('data-mobile-nav-item="history"')
        ->toContain('data-mobile-nav-item="menu"')
        ->toContain('data-mobile-account-menu')
        ->toContain('class="absolute right-0 top-full z-[60]')
        ->toContain('class="absolute right-0 top-full')
        ->toContain('data-mobile-header-wallet-balance')
        ->toContain('data-mobile-login')
        ->toContain('data-mobile-account-menu-panel')
        ->toContain('data-mobile-sidebar-footer')
        ->toContain('data-mobile-sidebar-logout')
        ->toContain('<form method="POST" action="{{ route(\'logout\') }}">')
        ->toContain('<span>Đăng xuất</span>')
        ->toContain('aria-controls="client-mobile-account-menu"')
        ->toContain('aria-label="Menu tài khoản trên di động"')
        ->toContain('data-account-menu')
        ->toContain('data-account-menu-toggle')
        ->toContain('data-account-menu-panel')
        ->and(substr_count($layout, 'data-account-menu>'))
        ->toBe(1)
        ->and(substr_count($layout, 'data-account-menu-toggle'))
        ->toBe(2)
        ->and($layout)
        ->toContain('data-account-support-link')
        ->and(substr_count($layout, 'data-account-support-link'))
        ->toBe(2)
        ->and($layout)
        ->toContain("route('client.support.chat')")
        ->toContain('data-header-wallet-balance')
        ->toContain('role="dialog"')
        ->toContain('aria-modal="true"')
        ->toContain('aria-haspopup="dialog"')
        ->toContain("route('home')")
        ->toContain("route('wallet.deposit.index')")
        ->toContain('<span class="truncate">Nạp game</span>')
        ->toContain('<span class="truncate">Lịch sử</span>')
        ->toContain('<span>Menu</span>')
        ->toContain('<span>Trang chủ</span>')
        ->toContain('<span>Nạp tiền</span>')
        ->toContain('<span>Lịch sử đơn hàng</span>')
        ->toContain('<span>Bài viết</span>')
        ->toContain("route('seo.index')")
        ->toContain("request()->routeIs(['content.contact', 'client.support.chat'])")
        ->toContain('<x-client.floating-support raised />')
        ->and($script)
        ->toContain("{ opacity: 0.82, transform: 'translateX(100%) scale(0.985)' }")
        ->toContain("const menuItems = () => [...panel.querySelectorAll('[data-menu-item]')]")
        ->toContain('delay: 70 + index * 35')
        ->toContain("document.querySelectorAll('[data-page-enter]')")
        ->toContain('animateAndRelease')
        ->toContain("document.body.classList.add('client-menu-open')")
        ->toContain("if (event.key === 'Escape')")
        ->toContain("event.key !== 'Tab'")
        ->toContain("window.matchMedia('(min-width: 1024px)')")
        ->toContain("window.addEventListener('pagehide', resetMenu)")
        ->toContain("document.querySelectorAll('[data-account-menu]')")
        ->toContain("event.key === 'Escape' && button.getAttribute('aria-expanded') === 'true'")
        ->toContain("event.key !== 'ArrowDown'")
        ->toContain("chevron?.classList.toggle('rotate-180', expanded)")
        ->and($styles)
        ->toContain('body.client-menu-open')
        ->toContain('overflow-x: clip;')
        ->toContain('body > main')
        ->toContain('@apply relative min-h-screen w-full max-w-full overflow-x-hidden')
        ->toContain('@apply mx-auto box-border w-full min-w-0 max-w-6xl px-3 sm:px-6 lg:px-8;')
        ->toContain('@apply w-full min-w-0 overflow-hidden rounded-[5px] border border-slate-200 bg-white shadow-sm;')
        ->toContain('@apply grid min-w-0 grid-cols-1 lg:grid-cols-[minmax(0,65fr)_minmax(20rem,35fr)];')
        ->toContain('@apply grid min-w-0 grid-cols-2 gap-2 min-[390px]:grid-cols-3 sm:grid-cols-4;')
        ->toContain('@media (min-width: 992px)')
        ->toContain('@apply table-fixed text-[11px] sm:min-w-[32rem] sm:table-auto sm:text-sm;')
        ->toContain('@apply min-w-[42rem] table-auto;')
        ->toContain('@apply block w-full min-w-0 max-w-full overflow-x-auto overscroll-x-contain;')
        ->toContain("[data-menu-toggle][aria-expanded='true'] [data-menu-icon-close]")
        ->toContain('@media (hover: hover) and (pointer: fine)')
        ->and($accountOrders)
        ->toContain('data-order-table')
        ->not->toContain('data-order-mobile-list')
        ->toContain('overflow-x-auto overscroll-x-contain')
        ->toContain('client-button w-full gap-2 sm:w-auto')
        ->and($accountProfile)
        ->toContain('data-account-tabs')
        ->toContain('data-account-tab-active')
        ->toContain('snap-x snap-mandatory')
        ->toContain('md:grid-cols-2 lg:grid-cols-3')
        ->toContain('Kéo ngang')
        ->and($script)
        ->toContain("document.querySelectorAll('[data-account-tabs]')")
        ->toContain('const activeTabBounds = activeTab.getBoundingClientRect()')
        ->toContain("tabs.scrollTo({ left: Math.max(0, left), behavior: 'auto' })")
        ->and($wallet)
        ->toContain('flex flex-col gap-3 p-4 sm:flex-row')
        ->and($topupGame)
        ->toContain('class="client-container py-8 sm:py-10 lg:py-12"')
        ->toContain("'selectedGame' => \$game")
        ->and($payment)
        ->toContain('<x-client.bank-transfer-payment')
        ->and($sharedPayment)
        ->toContain('grid min-w-0 grid-cols-1 gap-5 lg:grid-cols-[320px_minmax(0,1fr)]')
        ->toContain('flex min-w-0 flex-col gap-4 sm:flex-row')
        ->and($contentPage)
        ->toContain('lg:grid-cols-[250px_minmax(0,1fr)]')
        ->and($seoIndex)
        ->toContain('flex min-w-0 flex-col gap-3 p-3 sm:flex-row')
        ->and($floatingSupport)
        ->toContain("route('client.support.chat')")
        ->toContain('data-floating-support')
        ->toContain('bx-message-circle-dots')
        ->not->toContain('bx-support')
        ->toContain('motion-safe:animate-ping')
        ->toContain('bottom-[calc(env(safe-area-inset-bottom)+6rem)]')
        ->toContain('Chat hỗ trợ')
        ->and($boxicons)
        ->toContain('.bx-message-circle-dots:before');
});
