<?php

test('client reward table is configurable and synchronized with the topup form', function (): void {
    $projectRoot = dirname(__DIR__, 2);
    $home = file_get_contents($projectRoot.'/resources/views/client/home/index.blade.php');
    $form = file_get_contents($projectRoot.'/resources/views/client/components/topup-form.blade.php');
    $script = file_get_contents($projectRoot.'/resources/js/client.js');
    $styles = file_get_contents($projectRoot.'/resources/css/client.css');
    $adminCatalog = file_get_contents($projectRoot.'/resources/js/pages/admin/topup/catalog/index.vue');

    expect($home)
        ->toContain('Bảng thực nhận theo từng game')
        ->toContain('data-game-reward-tab="{{ $game->id }}"')
        ->toContain('data-game-reward="{{ $game->id }}"')
        ->toContain('<th scope="col">Nhóm</th>')
        ->toContain('<th scope="row">{{ $game->reward_label ?: \'Thực nhận\' }}</th>')
        ->toContain('data-package-column="{{ $package->id }}"')
        ->toContain('role="region" aria-label="Bảng thực nhận {{ $game->name }}"')
        ->toContain("{{ \$game->reward_label ?: 'Thực nhận' }}")
        ->toContain('{{ $package->denomination ? number_format($package->denomination')
        ->toContain('{{ $package->reward_x2_amount !== null')
        ->toContain('{{ $package->reward_x3_amount !== null')
        ->toContain('{{ $package->first_topup_reward_amount !== null')
        ->not->toContain('$package->provider_price')
        ->and($form)
        ->toContain('bx bx-joystick')
        ->toContain('bx bx-coins')
        ->toContain('bx bx-user')
        ->toContain('bx bx-group')
        ->toContain('bx bx-credit-card')
        ->toContain('data-package-button="{{ $package->id }}"')
        ->toContain('data-purchase-tab="single"')
        ->toContain('data-purchase-tab="bulk"')
        ->toContain('role="tabpanel"')
        ->toContain('data-server-picker="single"')
        ->toContain('data-server-picker="bulk"')
        ->toContain("->push('Số lượng')")
        ->toContain('data-bulk-placeholder="{{ $fieldPlaceholders }}"')
        ->toContain('data-bulk-account-count')
        ->toContain('data-bulk-count')
        ->toContain('data-quantity-decrease')
        ->toContain('data-quantity-increase')
        ->toContain('data-summary-package')
        ->toContain('data-summary-reward')
        ->toContain('data-submit-text')
        ->not->toContain('⬆')
        ->and($script)
        ->toContain("const packageButtons = Array.from(form.querySelectorAll('[data-package-button]'))")
        ->toContain("topupPackage.dispatchEvent(new Event('change', { bubbles: true }))")
        ->toContain("const purchaseTabs = Array.from(form.querySelectorAll('[data-purchase-tab]'))")
        ->toContain('syncPurchaseMode(tab.dataset.purchaseTab)')
        ->toContain("const serverPickers = Array.from(form.querySelectorAll('[data-server-picker]'))")
        ->toContain('picker.required = active')
        ->toContain('const matchesServer = !serverId || !button.dataset.packageServer || button.dataset.packageServer === serverId')
        ->toContain('const matchesServer = !serverId || !option.dataset.server || option.dataset.server === serverId')
        ->toContain('const hasServer = Boolean(server?.value)')
        ->toContain("? 'CHỌN MÁY CHỦ'")
        ->toContain("const bulkAccountCount = form.querySelector('[data-bulk-account-count]')")
        ->toContain("bulkRecipients.placeholder = activeSchema?.dataset.bulkPlaceholder || ''")
        ->toContain('return /^[1-9]\\d*$/.test(value) ? totalQuantity + Number(value) : totalQuantity')
        ->toContain("quantityDecrease?.addEventListener('click'")
        ->toContain('submitText.textContent = !hasServer')
        ->toContain("document.querySelectorAll('[data-package-row], [data-package-column]')")
        ->toContain("const rewardTabs = Array.from(document.querySelectorAll('[data-game-reward-tab]'))")
        ->toContain("game.dispatchEvent(new Event('change', { bubbles: true }))")
        ->toContain("['ArrowLeft', 'ArrowRight', 'Home', 'End']")
        ->and($styles)
        ->toContain('.home-checkout-layout')
        ->toContain(".home-purchase-tabs [role='tab'][aria-selected='true']")
        ->toContain(".home-package-option[aria-pressed='true']")
        ->toContain('.home-order-summary')
        ->toContain(".home-game-tab[aria-selected='true']")
        ->toContain('.home-reward-table')
        ->toContain('.home-reward-table th:first-child')
        ->toContain('.home-reward-table [data-package-column].is-selected')
        ->and($adminCatalog)
        ->toContain('v-model.trim="form.reward_label"')
        ->toContain('v-model="form.reward_x2_amount"')
        ->toContain('v-model="form.reward_x3_amount"')
        ->toContain('v-model="form.first_topup_reward_amount"');
});
