<?php

test('client reward table is configurable and synchronized with the topup form', function (): void {
    $projectRoot = dirname(__DIR__, 2);
    $home = file_get_contents($projectRoot.'/resources/views/client/home/index.blade.php');
    $form = file_get_contents($projectRoot.'/resources/views/client/components/topup-form.blade.php');
    $script = file_get_contents($projectRoot.'/resources/js/client.js');
    $styles = file_get_contents($projectRoot.'/resources/css/client.css');
    $adminCatalog = file_get_contents($projectRoot.'/resources/js/pages/admin/topup/catalog/index.vue');

    expect($home)
        ->toContain('Bảng thực nhận theo từng game')
        ->toContain('data-game-reward-tab="{{ $game->id }}"')
        ->toContain('data-game-reward="{{ $game->id }}"')
        ->toContain('<th scope="col">Mệnh giá</th>')
        ->toContain('<th scope="col">Đơn vị nhận</th>')
        ->toContain('data-reward-denomination="{{ $setting->denomination }}"')
        ->toContain('role="region" aria-label="Bảng thực nhận {{ $game->name }}"')
        ->toContain('$game->globalPackageSettings')
        ->toContain("data_get(\$receive, 'reward_x2_amount')")
        ->toContain("data_get(\$receive, 'reward_x3_amount')")
        ->toContain("data_get(\$receive, 'first_topup_reward_amount')")
        ->not->toContain('$package->provider_price')
        ->and($form)
        ->toContain('bx bx-joystick')
        ->toContain('bx bx-coins')
        ->toContain('bx bx-user')
        ->toContain('bx bx-group')
        ->toContain('bx bx-credit-card')
        ->toContain('data-package-button="{{ $package->id }}"')
        ->toContain('data-purchase-tab="single"')
        ->toContain('data-purchase-tab="bulk"')
        ->toContain('role="tabpanel"')
        ->toContain('data-server-picker="single"')
        ->toContain('data-server-picker="bulk"')
        ->toContain('data-name="{{ $game->name }}"')
        ->toContain('{{ $game->name }} - ID: {{ $game->id }}')
        ->toContain('{{ $server->name }} - ID: {{ $server->id }}')
        ->toContain("->push('Số lượng thẻ')")
        ->toContain('data-bulk-placeholder="{{ $fieldPlaceholders }}"')
        ->toContain('data-bulk-account-count')
        ->toContain('data-bulk-count')
        ->toContain('data-bulk-format-error')
        ->toContain('data-quantity-decrease')
        ->toContain('data-quantity-increase')
        ->toContain('data-summary-package')
        ->toContain('data-summary-reward')
        ->toContain('data-rewards="{{ json_encode($package->rewardItems')
        ->toContain('data-submit-text')
        ->not->toContain('⬆')
        ->and($script)
        ->toContain("const packageButtons = Array.from(form.querySelectorAll('[data-package-button]'))")
        ->toContain("topupPackage.dispatchEvent(new Event('change', { bubbles: true }))")
        ->toContain("const purchaseTabs = Array.from(form.querySelectorAll('[data-purchase-tab]'))")
        ->toContain('syncPurchaseMode(tab.dataset.purchaseTab)')
        ->toContain("const serverPickers = Array.from(form.querySelectorAll('[data-server-picker]'))")
        ->toContain('picker.required = active')
        ->not->toContain('button.dataset.packageServer')
        ->not->toContain('option.dataset.server')
        ->toContain('const hasServer = Boolean(server?.value)')
        ->toContain("? 'CHỌN MÁY CHỦ'")
        ->toContain("const bulkAccountCount = form.querySelector('[data-bulk-account-count]')")
        ->toContain("bulkRecipients.placeholder = activeSchema?.dataset.bulkPlaceholder || ''")
        ->toContain("line.includes('|')")
        ->toContain('bulkRecipients?.setCustomValidity(formatMessage)')
        ->toContain("bulkRecipients?.setAttribute('aria-invalid', String(hasInvalidRows))")
        ->toContain('!bulkResult.hasInvalidRows')
        ->toContain('bulkResult.hasInvalidRows ? 0 : bulkResult.quantity')
        ->toContain('`KIỂM TRA DÒNG ${bulkResult.firstInvalidLine}`')
        ->toContain("JSON.parse(option?.dataset.rewards || '[]')")
        ->toContain("formatRewards('base_amount')")
        ->toContain("quantityDecrease?.addEventListener('click'")
        ->toContain('submitText.textContent = !hasServer')
        ->toContain("document.querySelectorAll('[data-package-row], [data-package-column]')")
        ->toContain("document.querySelectorAll('[data-reward-denomination]')")
        ->toContain('element.dataset.rewardDenomination === denomination')
        ->toContain("const rewardTabs = Array.from(document.querySelectorAll('[data-game-reward-tab]'))")
        ->toContain('selectedGame?.dataset.name')
        ->toContain("game.dispatchEvent(new Event('change', { bubbles: true }))")
        ->toContain("['ArrowLeft', 'ArrowRight', 'Home', 'End']")
        ->and($styles)
        ->toContain('.home-checkout-layout')
        ->toContain(".home-purchase-tabs [role='tab'][aria-selected='true']")
        ->toContain(".home-package-option[aria-pressed='true']")
        ->toContain('.home-order-summary')
        ->toContain(".home-game-tab[aria-selected='true']")
        ->toContain('.home-reward-table')
        ->toContain('.home-reward-table th:first-child')
        ->toContain('.home-reward-table [data-package-column].is-selected')
        ->toContain('.home-reward-table [data-reward-denomination].is-selected > th')
        ->and($adminCatalog)
        ->toContain('v-model.trim="form.reward_label"')
        ->not->toContain('v-model="form.carot_amount"')
        ->not->toContain('v-model="form.reward_x2_amount"')
        ->not->toContain('v-model="form.reward_x3_amount"')
        ->not->toContain('v-model="form.first_topup_reward_amount"')
        ->not->toContain('Bảng thực nhận trong game')
        ->not->toContain('v-model="form.global_topup_package_id"')
        ->not->toContain('adminTopupService.globalPackages()')
        ->not->toContain('Chưa ánh xạ')
        ->not->toContain('v-model="form.game_server_id"')
        ->not->toContain('v-model="filters.game_server_id"');
});
