<?php

test('admin game service menu exposes all management pages', function (): void {
    $projectRoot = dirname(__DIR__, 2);
    $navigation = file_get_contents($projectRoot.'/resources/js/layouts/admin/sidebar/navigation.ts');
    $router = file_get_contents($projectRoot.'/resources/js/router/modules/admin/index.ts');

    expect($navigation)
        ->toContain("key: 'game-services'")
        ->toContain("label: 'Dịch vụ game'")
        ->toContain("{ label: 'Quản lý game', href: '/admin/game-services/games' }")
        ->toContain("{ label: 'Quản lý dịch vụ', href: '/admin/game-services/services' }")
        ->toContain("{ label: 'Gói dịch vụ', href: '/admin/game-services/packages' }")
        ->toContain("{ label: 'Quản lý đơn order', href: '/admin/game-services/orders' }")
        ->toContain("{ label: 'Quản lý chat', href: '/admin/game-services/chats' }")
        ->and($router)
        ->toContain("name: 'admin.game-services.games'")
        ->toContain("name: 'admin.game-services.services'")
        ->toContain("name: 'admin.game-services.packages'")
        ->toContain("name: 'admin.game-services.orders'")
        ->toContain("name: 'admin.game-services.chats'");
});

test('admin game service pages connect catalog payload prices servers and orders', function (): void {
    $projectRoot = dirname(__DIR__, 2);
    $catalog = file_get_contents($projectRoot.'/resources/js/pages/admin/game-services/catalog/index.vue');
    $orders = file_get_contents($projectRoot.'/resources/js/pages/admin/game-services/orders/index.vue');
    $service = file_get_contents($projectRoot.'/resources/js/services/admin-game-service.service.ts');

    expect($catalog)
        ->toContain('game_services_enabled')
        ->toContain("import DataTable from '@/components/shared/DataTable/index.vue'")
        ->toContain("import Modal from '@/components/shared/Modal/index.vue'")
        ->toContain('<Modal v-model="serviceModalOpen"')
        ->toContain('<Modal v-model="packageModalOpen"')
        ->toContain('<DataTable')
        ->toContain('openCreateServiceModal()')
        ->toContain('openCreatePackageModal()')
        ->toContain('serviceForm.background_image')
        ->toContain('@uploaded="serviceForm.background_image = $event"')
        ->toContain(':src="row.background_image"')
        ->toContain('payload_fields')
        ->toContain('serviceForm.seo_content')
        ->toContain('serviceForm.faqs')
        ->toContain('Bài SEO dịch vụ')
        ->toContain('<option value="password">Password</option>')
        ->toContain('server_ids')
        ->toContain('packageForm.prices')
        ->toContain('packageForm.prices.slice(0, 1)')
        ->toContain('Cấu hình giá')
        ->not->toContain('packageForm.prices.push(blankPrice())')
        ->not->toContain('packageForm.prices.splice')
        ->toContain(':data="displayedPackageRows"')
        ->toContain('v-model="packageGameFilter"')
        ->toContain('item.service.game_id === Number(packageGameFilter.value)')
        ->toContain('Tất cả game')
        ->toContain('v-if="catalogType !== \'packages\'"')
        ->toContain('placeholder="Nhập tên hoặc mã gói..."')
        ->toContain('@click="clearPackageFilters"')
        ->toContain(':columns="packageColumns"')
        ->toContain('form="game-service-package-form"')
        ->toContain('v-model="packageForm.game_id"')
        ->toContain('v-model="packageForm.game_service_id"')
        ->toContain('v-for="service in availablePackageServices"')
        ->toContain(':disabled="!packageForm.game_id"')
        ->toContain('price.collaborator_price')
        ->toContain('price.quantity_enabled')
        ->toContain('price.quantity_enabled ? Number(price.min_quantity) : 1')
        ->not->toContain('v-model.trim="price.code"')
        ->not->toContain('v-model="price.status"')
        ->not->toContain('price.status ===')
        ->not->toContain('Cho phép đặt')
        ->not->toContain('v-model.trim="price.label"')
        ->toContain('saveService')
        ->toContain('savePackage')
        ->and($orders)
        ->toContain('selectedOrder.payload')
        ->toContain('saveOrder')
        ->toContain('admin_note')
        ->toContain('Chi phí trả CTV')
        ->toContain('Thuế dự kiến')
        ->toContain('Lãi / lỗ ròng')
        ->toContain('settlement.net_profit')
        ->toContain('data-order-settlement-table')
        ->toContain('order.collaborator_total_cost')
        ->toContain('order.gross_profit')
        ->toContain('order.estimated_tax')
        ->toContain('order.net_profit')
        ->toContain("order.net_profit < 0 ? 'text-rose-700' : 'text-emerald-700'")
        ->not->toContain('text-violet-700')
        ->and($service)
        ->toContain("'/api/admin-api/game-service-games'")
        ->toContain("'/api/admin-api/game-services'")
        ->toContain("'/api/admin-api/game-service-packages'")
        ->toContain("'/api/admin-api/game-service-orders'")
        ->toContain('background_image: string | null')
        ->toContain("type: 'text' | 'number' | 'password' | 'select'");
});
